name: Ping Url
description: Ping url until maximum trials have exceeded.If result is not 200 then, fails the actions.

inputs:
  url: # INPUT_URL
    description: Url to ping.
    required: true
  max_trials: # INPUT_MAX_TRIALS
    description: Maximum number of trials until action fails
    default: '10'
    required: false
  delay: # INPUT_DELAY
    description: Delay in seconds between trials.
    default: '5'
    required: false

runs:
  using: docker
  image: Dockerfile
  