name: 08 - using variables

on: 
  
  workflow_dispatch:
    
env: 
  WORKFLOW_VAR: ' I am a workflow env var'
  OVERWRITTEN: 'I will be overwritten'
  UNDEFINED:  'vars.UNDEFINED_VAR'
jobs:
  echo:
    runs-on: ubuntu-latest
    env: 
      JOB_VAR: 'I am a job env var'
      OVERWRITTEN: 'I have been overwritten at the job level'
    steps:
      - name: print Env variables
        env: 
          STEP_VAR: "I am an env step var"
          step_var2: "I am a lowercase stepvar"
        run: |
          echo "step env var: ${{ env.STEP_VAR }}"
          echo "step env var 2: $step_var2"
          echo "job env var: ${{ env.JOB_VAR }}"
          echo "workflow env var: ${{ env.WORKFLOW_VAR }}"
          echo "overwritten env var: ${{ env.OVERWRITTEN }}"
      - name: Overwrite job variable
        env:
          OVERWRITTEN: 'I have been overwritten at the step level'
        run: |
          echo "step env var: ${{ env.OVERWRITTEN }}"

  echo2: 
      runs-on: ubuntu-latest
      steps:
        - name: Print Variables
          run: |
            echo "Org var: ${{ vars.ORG_VAR }}
            echo "Overwritten var: ${{ vars.OVERWRITTEN_VAR }}
            echo "Repository var: ${{ vars.REPOSITORY_VAR }}
  echo-prod: 
     runs-on: ubuntu-latest
     environment: prod
     steps:
       - name: Print Prod Variables
         run: |
           echo "Org var: ${{ vars.ORG_VAR }}
           echo "Overwritten var: ${{ vars.OVERWRITTEN_VAR }}
           echo "Repository var: ${{ vars.REPOSITORY_VAR }}
           echo "Environment var: ${{ vars.TARGET_VAR }}
  echo-undefined: 
    runs-on: ubuntu-latest
    steps:
        - name: Print Undefined Variables
          run: | 
            echo "Org var: ${{ vars.UNDEFINED_VAR || 'default value' }}
            
