name: 15 - working with matricies

on:
  workflow_dispatch:

jobs:
  backwards_compatibility:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x, 20.x, 21.x]
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            node-version: 16.x
          - os: ubuntu-latest
            node-version: 21.x
            tag: experimental

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fail if experimental
        if: matrix.tag == 'experimental'
        run: exit 1

      - name: Perform tests
        run: |
          echo "running tests on os ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
          sleep 10
      
      - name: Upload results
        run: echo "Uploading test results"