name: 18.1 Reusable workflows - Reusable Definition

on:
  workflow_call:
    inputs:
      target-directory:
        type: string
        required: true
    outputs: 
      build-status:
        description: The status of the build process
        value: ${{ jobs.deploy.ouputs.build-status }}
      url:
        description: The url of the deployed version
        value: ${{ jobs.deploy.ouputs.url }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.ouputs.build-status }}
      url: ${{ steps.deploy.outputs.url }}
        
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Build
          id: build
          run: |
            echo "building using directory ${{ inputs.target-directory }}"
            echo "build-status=success" >> "$GITHUB_OUTPUT"
        - name: Deploy
          id: deploy 
          run: |
            echo "Deploying Build Artifacts" 
            echo "url=https://www.google.com" >> "$GITHUB_OUTPUT"   
